---
title: "Intro to time series wrangling and viz"
author: "AJ Zekanoski"
date: "2/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(lubridate)
library(tsibble)
library(feasts)
library(slider)
```


## Read in the data

```{r}
toolik <- read_csv(here("data",
                        "toolikweather.csv"))

```

### Convert this into a tsibble

```{r}
toolik_ts <- toolik %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  as_tsibble(key = NULL, index = date)
```

```{r}
ggplot(data = toolik_ts, aes(x = date, y = mean_airtemp)) +
  geom_line()
```

## Use `index_by()` function to aggregate time series information by intervals we specify. 

```{r}
toolik_month <- toolik_ts %>% 
  index_by(yr_mo = ~yearmonth(.)) %>% 
  summarise(monthly_mean_temp = mean(mean_airtemp, na.rm = TRUE))
```

```{r}
ggplot(data = toolik_month, aes(x = yr_mo, y = monthly_mean_temp)) +
  geom_line() +
  facet_wrap(~month(yr_mo, label = TRUE))
```

Aggregate by week: 
```{r}
toolik_weekly <- toolik_ts %>% 
  index_by(weekly = ~yearweek(.)) %>% 
  summarise(weekly_airtemp = mean(mean_airtemp, na.rm = TRUE))
```

## Filtering time series

Use `filter_index()` to specify ranges of time series to keep or exclude.

```{r}
toolik_ts %>% 
  filter_index("2000-06" ~ "2001-10")
```

```{r}
toolik_ts %>% 
  filter_index("2006-04-10" ~ "2006-05-15")
```

## Seasonplots

```{r}
toolik_ts %>% 
  filter(year(date) > 2014) %>% 
  gg_season(y = mean_airtemp)

toolik_month %>% 
  gg_season(y = monthly_mean_temp) +
  theme_light()
```

